{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf500
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 #!/usr/bin/env python\
\
pipeline \{\
  agent any \
  parameters \{\
    string (defaultValue: '/Users/b0097042/Downloads/AirtelXstream-release-1.30.3-12657-playStore.apk', description: '', name: 'INPUT_LOCATION', trim: true)\
    string (defaultValue: '76c7a771e3f8ffdd99e829b71f1a3ed6319ce08db1831a641cf1978c659bac24', description: '', name: 'AUTH_KEY', trim: true)\
  \}\
  \
    stages \{\
    stage('Analysis') \{\
    steps \{\
      script \{\
            upload_cmd = "curl -s -S -F 'file=@$\{env.INPUT_LOCATION\}' http://localhost:8000/api/v1/upload -H 'Authorization:$\{env.AUTH_KEY\}'"\
            upload_result = sh label: 'Upload Binary', returnStdout: true, script: upload_cmd\
                      \
            def response_map = readJSON text: upload_result\
            def app_type = response_map["scan_type"]\
            def app_hash = response_map["hash"]\
            def app_name = response_map["file_name"]\
                      \
            scan_start_cmd = "curl -s -S -X POST --url http://localhost:8000/api/v1/scan --data 'scan_type=$\{app_type\}&file_name=$\{app_name\}&hash=$\{app_hash\}' -H 'Authorization:$\{env.AUTH_KEY\}'"\
            sh label: 'Start Scan of Binary', returnStdout: true, script: scan_start_cmd\
            \
//            sh "qark --apk $\{env.INPUT_LOCATION\}"\
            report = "curl POST --url http://localhost:8000/api/v1/download_pdf --data 'hash=$\{app_hash\}&scan_type=$\{app_type\}' -H 'Authorization:$\{env.AUTH_KEY\}' > Report.pdf"\
            sh label: 'Generate PDF', returnStdout: true, script: report\
            \
            jsonData = "curl POST --url http://localhost:8000/api/v1/report_json --data 'hash=$\{app_hash\}&scan_type=$\{app_type\}' -H 'Authorization:$\{env.AUTH_KEY\}' > Report.json"\
            sh label: 'Generate JSON', returnStdout: true, script: jsonData\
            \
            archive (includes: '*.pdf')\
            archive (includes: '*.json')\
            \}\
        \}\
      \}\
    \}\
  \} \
}
